version: '3'
services:
        awms:
                image: albertokarakoutev/awms:1.0.2
                ports: 
                        - 8444:8443
                links: 
                        - awms-mongodb:awms-mongodb
                restart: always
                env_file:
                        - .env
                depends_on:
                        - awms-mongodb
        awms-mongodb:
                image: albertokarakoutev/awms-mongodb:1.0.2
                ports: 
                        - 27017:27017
                env_file:
                        - .env
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
                        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
                volumes:
                        - awms-mongo-data:/data/db
        awms-mongo-express:
                image: mongo-express
                restart: always
                ports: 
                        - 8080:8081
                env_file:
                        - .env
                environment:
                        - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
                        - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PASSWORD}
                        - ME_CONFIG_MONGODB_SERVER=awms-mongodb
                        - ME_CONFIG_MONGODB_PORT=${MONGO_DB_PORT}
                        - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_DB_AUTH_DATABASE}
                depends_on:
                        - awms-mongodb
volumes:
        awms-mongo-data:
                driver: local

